apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    juancvilla/name: hw-example
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      juancvilla/name: hw-example
  template:
    metadata:
      labels:
        juancvilla/name: hw-example
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:2.0
        name: hello-world
        ports:
        - containerPort: 8080
